### Site Settings ###
title               : Andréa Joly
description         : >-
                      Data Scientist apprentice,<br>
                      Interested in ML/AI,<br> 
                      Passionate about IT and aviation
baseurl             : ""
repository          : Andreaj42/Andreaj42.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Andréa Joly
  image             : images/identity.jpg
  email             : administrateur@andrea-joly.fr
  github            : Andreaj42
  instagram         : andrea42130
  linkedin          : andréa-joly
# gitlab            : your_username
# medium            : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"

favicon: /assets/favicon.ico

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
