### Site Settings ###
title               : Andréa Joly
description         : >-
                      Data Scientist apprentice,<br>
                      Interested in ML/AI,<br> 
                      Passionate about IT and aviation
baseurl             : ""
repository          : Andreaj42/Andreaj42.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Andréa Joly
  image             : images/identity.jpg
  email             : no-reply@andrea-joly.fr
  github            : Andreaj42
# gitlab            : your_username
  instagram         : andrea42130
  linkedin          : andréa-joly
# medium            : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
